import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <nav className={styles.button}>
        <Link href="/">
          <a>Home</a>
        </Link>
      </nav>

      <main className={styles.margins12}>
        <h3>About Page</h3>
      </main>

      <footer>
        <div className={[styles.footer, styles.bar].join(" ")}>Footer</div>
      </footer>
    </div>
  )
}

export default About
