import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Counter from '../features/counter/Counter'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.button}>
        <Link href="/about">
          <a>About</a>
        </Link>
      </nav>

      <main>
        <h3 className={styles.margins12}>Home Page</h3>
        <Counter />
      </main>

      <footer>
      <div className={[styles.footer, styles.bar].join(" ")}>Footer</div>
      </footer>
    </div>
  )
}

export default Home
